*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1608M(0603)/X7R/0.1uF/100V
* Murata P/N :GRM188R72A104KA35
* Property : C = 0.1[uF]
* Data Generated on Nov 6, 2018
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100Hz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM188R72A104KA35_DC0V_25degC port1 port2
C1 port1 11 9.94e-8
L2 11 12 1.68e-10
R3 12 13 1.35e-2
C4 13 14 1.39e-5
R4 13 14 285
C5 14 15 2.35e-5
R5 14 15 28.5
C6 15 16 1.88e-5
R6 15 16 7.00
C7 16 17 1.68e-5
R7 16 17 9.47e-1
C8 17 18 1.50e-5
R8 17 18 1.51e-1
C9 18 19 1.07e-5
R9 18 19 2.98e-2
C10 19 20 1.31e-5
R10 19 20 3.83e-3
L11 20 21 1.43e-11
R11 20 21 8.15e-2
L12 21 22 1.08e-10
R12 21 22 7.26e-2
C13 22 23 4.76e-7
L13 22 23 2.94e-11
R13 22 23 3.05e-2
C14 23 24 1.58e-7
L14 23 24 2.63e-11
R14 23 24 2.63e-2
C15 24 port2 3.33e-12
L15 24 port2 1.14e-10
R15 24 port2 22.5
R100 port1 11 5.00e+9
.ENDS GRM188R72A104KA35_DC0V_25degC