*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :3216M(1206)/X7R/4.7uF/100V
* Murata P/N :GRM31CZ72A475KE11
* Property : C = 4.7[uF]
* Data Generated on Sep 11, 2017
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100Hz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM31CZ72A475KE11_DC0V_25degC port1 port2
C1 port1 11 4.58e-6
L2 11 12 9.45e-11
R3 12 13 3.22e-3
C4 13 14 3.81e-4
R4 13 14 13.0
C5 14 15 4.23e-4
R5 14 15 1.08
C6 15 16 3.47e-4
R6 15 16 1.62e-1
C7 16 17 3.18e-4
R7 16 17 1.77e-2
C8 17 18 2.53e-4
R8 17 18 2.05e-3
L9 18 19 1.30e-11
R9 18 19 5.80e-2
L10 19 20 4.79e-11
R10 19 20 2.60e-2
L11 20 21 3.43e-10
R11 20 21 2.38e-2
C12 21 22 1.04e-5
L12 21 22 1.19e-10
R12 21 22 1.09e-2
C13 22 23 5.17e-6
L13 22 23 8.47e-11
R13 22 23 9.06e-3
C14 23 24 1.36e-11
L14 23 24 6.70e-11
R14 23 24 12.6
C15 24 port2 1.56e-12
L15 24 port2 2.89e-10
R15 24 port2 139
R100 port1 11 1.06e+7
.ENDS GRM31CZ72A475KE11_DC0V_25degC